# Generated by Django 4.0 on 2021-12-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('last', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('selective_status', models.CharField(choices=[('обнаружено', 'обнаружено'), ('не обнаружено', 'не обнаружено')], max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('мужской', 'мужской'), ('женщина', 'женщина')], max_length=20)),
                ('address', models.CharField(max_length=70)),
                ('id_service', models.CharField(max_length=20, unique=True)),
                ('id_patient', models.CharField(max_length=20, unique=True)),
                ('reference_intervals', models.CharField(max_length=50)),
                ('result_date', models.DateTimeField()),
                ('biomaterial_data', models.DateTimeField()),
                ('date_registrations', models.DateTimeField()),
            ],
        ),
    ]
